### ISSUE TITLE
Jobs based on fixed schedule

### ISSUE THREAD

**Issue by greyblake** [sidekiq-scheduler/sidekiq-scheduler#3]
Allow to define scheduled jobs based on fixed schedule like ResqueScheduler do:

schedule.yml:

``` yaml
CancelAbandonedOrders:
  cron: "*/5 * * * *"

queue_documents_for_indexing:
  cron: "0 0 * * *"
  class: QueueDocuments
  queue: high
  args:
  description: "Job"
```

Somewhere in application:

``` ruby
Sidekiq.schedule = YAML.load_file("schedule.yml")
```

Please let me know if it's implemented. I looked through documentation and source code but found nothing.
