### ISSUE TITLE
Document config/sidekiq.yml syntax

### ISSUE THREAD

**Issue by felixbuenemann** [sidekiq-scheduler/sidekiq-scheduler#32]
The README mentions that it's possible to store the schedules in config/sidekiq.yml, but it doesn't tell you what key to use. So it would be nice to have an example.

Eg. a config might look like:

``` yaml

---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - default
  - process_asset
staging:
  :concurrency: 5
  :tag: myapp_staging
  :queues:
    - default
    - export
    - process_asset
    - import
production:
  :concurrency: 25
  :tag: myapp_production
  :queues:
    - default
    - export
    - process_asset
    - import
```

It would make sense to be possible to define schedules like this:

``` yaml

---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - default
  - process_asset
:schedules:
  AssetWorker:
    every: 15m
staging:
  :concurrency: 5
  :tag: myapp_staging
  :queues:
    - default
    - export
    - process_asset
    - import
  :schedules:
    AssetWorker:
      every: 60m
    ImportWorker:
      every: 1m
    ExportWorker:
      every: 1m
production:
  :concurrency: 25
  :tag: myapp_production
  :queues:
    - default
    - export
    - process_asset
    - import
  :schedules:
    AssetWorker:
      every: 2h
    ImportWorker:
      every: 15m
    ExportWorker:
      every: 15m
```

The idea is that you can define a default schedule and override per environment.
