### ISSUE TITLE
Schedule not being reloaded when starting Rails app

### ISSUE THREAD

**Issue by shedd** [sidekiq-scheduler/sidekiq-scheduler#35]
I'm seeing an issue where restarting the Rails app does not reload the schedule.

Following the README example, I have an initializer that loads `config/schedule.yml`

```
require 'sidekiq/scheduler'
Sidekiq.schedule = YAML.load_file(File.expand_path('../../../config/schedule.yml', __FILE__))
```

If the following is my `schedule.yml`

```
vagrant@precise64:/vagrant$ cat config/schedule.yml
############################################################################
# Defines the schedule of recurring Sidekiq jobs
# See https://github.com/Moove-it/sidekiq-scheduler for more information
############################################################################

# run, every minute, the job to look for delayed orders
queue_delayed_order_notifications:
  every: ["1m"]
  class: DelayedOrderNotifications
  description: "This job looks for delayed orders and triggers the appropriate notifications"
```

It loads fine:

```
vagrant@precise64:/vagrant$ bundle exec rails c
Loading development environment (Rails 4.1.2)
[1] pry(main)> Sidekiq.schedule
=> {"queue_delayed_order_notifications"=>
  {"every"=>["1m"],
   "class"=>"DelayedOrderNotifications",
   "description"=>"This job looks for delayed orders and triggers the appropriate notifications"}}
```

However, if I change the schedule - so changing from `1m` to `1h`:

```
vagrant@precise64:/vagrant$ cat config/schedule.yml
############################################################################
# Defines the schedule of recurring Sidekiq jobs
# See https://github.com/Moove-it/sidekiq-scheduler for more information
############################################################################

# run, every minute, the job to look for delayed orders
queue_delayed_order_notifications:
  every: ["1h"]
  class: DelayedOrderNotifications
  description: "This job looks for delayed orders and triggers the appropriate notifications"
```

Then I reload Rails:

```
vagrant@precise64:/vagrant$ bundle exec rails c
Loading development environment (Rails 4.1.2)
[1] pry(main)> Sidekiq.schedule
=> {"queue_delayed_order_notifications"=>
  {"every"=>["1m"],
   "class"=>"DelayedOrderNotifications",
   "description"=>"This job looks for delayed orders and triggers the appropriate notifications"}}
```

The schedule has not changed.  It's still `1m` in Sidekiq, even though I've completely reloaded the app.

In fact, in my Vagrant development environment, the only thing that I found to reload the schedule is actually to reboot the VM.

Is this expected?  I've used Resque scheduler before, so I'm expecting behavior similar to that - with Resque scheduler, the schedule was loaded fresh every time the Rails app was restarted.
