### ISSUE TITLE
When `include_metadata: true`, `Sidekiq.strict_args!` fails with "Job arguments must be native JSON types"

### ISSUE THREAD

**Issue by craigmcn** [sidekiq-scheduler/sidekiq-scheduler#402]
I'm getting a Sidekiq error message "Job arguments must be native JSON types" when I include the `include_metadata: true` option in my schedule. The specific error is:
"ArgumentError: Job arguments to Actions::System::DestroyOldUserSessions must be native JSON types, see https://github.com/mperham/sidekiq/wiki/Best-Practices.
To disable this error, remove `Sidekiq.strict_args!` from your initializer."

Without `Sidekiq.strict_args!`, I get a deprecation warning:
"WARN: Job arguments to Actions::System::DestroyOldUserSessions do not serialize to JSON safely. This will raise an error in
Sidekiq 7.0. See https://github.com/mperham/sidekiq/wiki/Best-Practices or raise an error today
by calling `Sidekiq.strict_args!` during Sidekiq initialization."

Removing `include_metadata: true` resolves the issue.

Ruby version: 2.7.5
Rails version: 7.0.3.1
Sidekiq version: 6.5.4
Sidekiq Scheduler version: 4.0.2

Sidekiq initializer:
```ruby
Sidekiq.configure_server do |config|
  # url format 'redis://redis.example.com:7372/0'
  config.redis = {url: ENV["REDIS_JOBS_URL"]}

  config.strict_args!
end
```

Sidekiq YAML:
```yml
production:
  :concurrency: 5
:queues:
  - actions
  - default
  - low
  - mailers
:schedule:
  revoke_old_user_session:
    description: "Revoke all user sessions that have not been accessed in the past 24 hrs"
    cron: "0 1 * * * America/Los_Angeles" # At 1 min after midnight everyday
    class: "Actions::System::RevokeOldUserSessions"
    include_metadata: true
    args: [
      { invoked_by: "system" }
    ]
  destroy_old_user_session:
    description: "Destroy user sessions that have been revoked over 1 year ago"
    cron: "0 3 * * * America/Los_Angeles" # At 3 min after midnight everyday
    class: "Actions::System::DestroyOldUserSessions"
    include_metadata: true
    args: [
      { invoked_by: "system" }
    ]
```

I believe I have a working PR that I will submit.
