### ISSUE TITLE
Run job multiple times, but never at the same time

### ISSUE THREAD

**Issue by wuarmin** [sidekiq-scheduler/sidekiq-scheduler#430]
Hey!

Thanks for this great gem! One question:
I want a job to run multiple times in a row, but never at the same time, no matter how long it takes.
I.e. I tried following
```yml
:scheduler:
  :schedule:
    test:
      interval: '1m' # interval one minute
      class: Bookshelf::Jobs::Test
```
 but Bookshelf::Jobs::Test sleeps for `115` secs
```ruby
module Bookshelf
  module Jobs
    class Test < PayNRed::Job
      def perform
        # simulate a long-running job
        sleep 115
      end
    end
  end
end
```
but with this the result are 2 busy jobs. Is it possible to specify that a job is not called if the old one is still running?
thanks and best regards
