### ISSUE TITLE
Sidekick (docker) deprecation warning

### ISSUE THREAD

**Issue by RPHllc** [sidekiq-scheduler/sidekiq-scheduler#450]
I am getting deprecation warning from sidekick. I am using docker compose with image:

```
sidekiq:
    image: tootsuite/mastodon:v4.1.4
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -c 1
```

 2023-07-13T19:47:05.560Z pid=6 tid=76a WARN: `config.options[:key] = value` is deprecated, use `config[:key] = value`: ["/opt/mastodon/lib/mastodon/redis_config.rb:38:in `<top (required)>'", "/opt/mastodon/config/application.rb:55:in `require_relative'"]

Something like this was reported earlier on, #384 , but this may be new as I am on current mastodon version 4.1.4.
