### ISSUE TITLE
[feature request] environment specific schedules

### ISSUE THREAD

**Issue by aaronmallen** [sidekiq-scheduler/sidekiq-scheduler#454]
I would love to see support for environment specific schedules in the config file like this:

```yaml
# config/sidekiq.yml

:queues:
  - critical
  - default
  - low
 
:scheduler:
  :schedule:
    :staging:
      DoAThing:
        every: 1 hour
    :production:
      DoAThing:
        every: 1 minute
```
