### ISSUE TITLE
keyword_argument: true do not work

### ISSUE THREAD

**Issue by DmitrySalnikov** [sidekiq-scheduler/sidekiq-scheduler#473]
Hello!

How do this functionality work?
```
# Deconstructs a hash defined as the `args` to keyword arguments. 
#
# `false` by default.
# 
# Example
# 
# my_job:
#   cron: '0 0 * * * *'
#   class: MyJob
#   args: { foo: 'bar', hello: 'world' } 
#   keyword_argument: true
#
# class MyJob < ActiveJob::Base
#   def perform(foo:, hello:)
#     # ...
#   end
# end
```

When I run a scheduler with keyword_argument: true and args as a hash I got an error:
```
ArgumentError at /recurring-jobs/job/enqueue
Job args must be an Array: { ...
```

**Comment by marcelolx** [comment]
Could you share what your configuration looks like? 

Here is the original issue where support for it was added https://github.com/sidekiq-scheduler/sidekiq-scheduler/issues/439

**Comment by DmitrySalnikov** [comment]
scheduler.yml
```
base_worker:
  class: Scheduler::BaseWorker
  cron: '0-59/10 1-23 * * *'
  args: { users: [23574], limit: 14 }
  keyword_argument: true
```
 
sidekiq.rb
```
Sidekiq.configure_server do |config|
  if ActiveModel::Type::Boolean.new.cast(ENV.fetch('IS_SCHEDULER', false))
    config.on(:startup) do
      Sidekiq.schedule = YAML.load_file(Rails.root.join('config', 'scheduler.yml').expand_path(File.dirname(__FILE__)))
      Sidekiq::Scheduler.reload_schedule!
    end
  end
end
```
