### ISSUE TITLE
v6.0.1 can't work with dynamic option

### ISSUE THREAD

**Issue by denysivanov** [sidekiq-scheduler/sidekiq-scheduler#504]
v6.0.1 can't work with dynamic option (sidekiq v8.0.1)

In given example if dynamic = **true** that job wouldn't be loaded to schedule

sidekiq.yml
```yml
:queues:
  - default

:scheduler:
  :schedule:
    sample_job:
      cron: '0 2 * * * America/New_York'
      class: SampleJob
  :dynamic: true
```

In given example if dynamic = **false** that job would be loaded to schedule

sidekiq.yml
```yml
:queues:
  - default

:scheduler:
  :schedule:
    sample_job:
      cron: '0 2 * * * America/New_York'
      class: SampleJob
  :dynamic: false
```
